import type { OxlintConfig } from 'oxlint';

const config: OxlintConfig = {
  ignorePatterns: [
    '**/node_modules/',
    '**/*.tsbuildinfo',
    '**/.npm',
    '**/.npmrc',
    '**/*.tgz',
    '**/coverage/',
    '**/dist/',
    '**/.stryker-tmp/',
    '**/reports/',
    '**/.env',
    '**/.env.*',
    '!**/.env.example',
    '**/.cache',
    '**/.parcel-cache',
    '**/.DS_Store',
    '**/node_modules',
    '**/dist',
    '**/package-lock.json',
    '**/yarn.lock',
    '**/pnpm-lock.yaml',
    '**/bun.lockb',
    '**/output',
    '**/coverage',
    '**/temp',
    '**/.temp',
    '**/tmp',
    '**/.tmp',
    '**/.history',
    '**/.vitepress/cache',
    '**/.nuxt',
    '**/.next',
    '**/.svelte-kit',
    '**/.vercel',
    '**/.changeset',
    '**/.idea',
    '**/.output',
    '**/.vite-inspect',
    '**/.yarn',
    '**/vite.config.*.timestamp-*',
    '**/CHANGELOG*.md',
    '**/*.min.*',
    '**/LICENSE*',
    '**/__snapshots__',
    '**/auto-import?(s).d.ts',
    '**/components.d.ts',
    'reports/**',
    'dist/**',
    '.stryker-tmp/**',
    'coverage/**',
    'node_modules/**',
    'pnpm-lock.yaml',
    '*.yml',
    '**/*.md',
    '**/*.mdx',
  ],
};

export default config;
